# config
title:  青春样 | yangzj1992's blog
subtitle:
author: yangzj1992
language: zh-Hans
email: yangzj1992@qq.com #联系邮箱
url: http://qcyoung.com

logo: http://qcyoung.qiniudn.com/qcyoung/TKL/logo.png
logoc: http://qcyoung.qiniudn.com/qcyoung/TKL/oursbrun.png
top_saying:
- title: GLAD TO SEE U, WELCOME TO YANGZJ1992 &#39;S BLOG.
- content: 每一个不曾起舞的日子都是对生命的辜负 —— 尼采 《查拉图斯特拉如是说》
bottom_saying:  奇迹每天都在发生 (Miracles happen every day) —— 《阿甘正传》
theme_pics_server: http://qcyoung.qiniudn.com/qcyoung/
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#Works
works:
# - works_name: AAA
#   works_url: /
# - works_name: BBB
#   works_url: /atom.xml

#duoshuo name
duoshuo_shortname: yangzj1992

# Disqus
disqus_shortname: yangzj1992

# Miscellaneous
GitHub: https://github.com/yangzj1992
Twitter: https://twitter.com/yangzj1992
Weibo: http://weibo.com/yangzj1992
ZhiHu: http://www.zhihu.com/people/yangzj1992
Shanbay: http://www.shanbay.com/bdc/review/progress/954313
Segmentfault: http://segmentfault.com/u/yangzj1992
Google: https://profiles.google.com/103095542128057560598
Baidu: http://www.baidu.com/p/yangzj1992

#Links
links:
- name: Contributions
  link: https://opensourcecontributo.rs/user/yangzj1992
  description: GitHub contributions
- name: Links
  link: http://qcyoung.com/links
  description: Friend Sites
- name: Life
  link: http://qcyoung.com/categories/%E6%88%91%E7%9A%84%E7%94%9F%E6%B4%BB/
  description: Work life

friendlinks:
- name: USTB
  link: http://www.ustb.edu.cn/
  description: 我的大学
- name: 美菜网
  link: http://meicai.cn/
  description: First Job
- name: Kieran
  link: http://go.kieran.top/
  description: 最初主题原创者
- name: DIYgod
  link: https://www.anotherhome.net/
  description: Write the Code. Change the World.
- name: Xcat Liu
  link: http://blog.xcatliu.com/
  description: A cat who writes code
- name: 寿百年
  link: http://www.pddjs.com/
  description: pddjs
- name: 朱嘉伟
  link: http://buzhundong.com/
  description: 单曲循环 | ΒΙΟG
- name: 个人博客导航
  link: http://blog.yiyeti.cc/hexo.html
  description: 为个人博客爱好者打造的资源导航站


#Project
projects:
- name: 掘金翻译计划
  link: https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E8%80%85%E7%A7%AF%E5%88%86%E8%A1%A8
- name: 众成翻译
  link: http://zcfy.cc/@yangzj1992/article
# - name: Resume
  # link: http://qcyoung.com/project/resume

#Analytics
cnzz: true  
cnzzaccount: 1000263347

